FROM docker.io/rockylinux:9

LABEL org.opencontainers.image.source=https://github.com/idiv-biodiversity/ansible-molecule-containers

# hadolint ignore=DL3041
RUN <<EOF
dnf update -y
dnf install -y systemd python3.12
dnf clean all

rm -fv /etc/systemd/system/*.wants/*
rm -fv /usr/lib/systemd/system/anaconda.target.wants/*
rm -fv /usr/lib/systemd/system/basic.target.wants/*
rm -fv /usr/lib/systemd/system/local-fs.target.wants/*
rm -fv /usr/lib/systemd/system/multi-user.target.wants/*
rm -fv /usr/lib/systemd/system/sockets.target.wants/*initctl*
rm -fv /usr/lib/systemd/system/sockets.target.wants/*udev*
rm -fv /usr/lib/systemd/system/sysinit.target.wants/systemd-tmpfiles-setup.service

systemctl set-default multi-user.target

systemctl enable dbus.socket

systemctl mask \
  dev-hugepages.mount \
  sys-fs-fuse-connections.mount \
  network.service \
  systemd-journal-flush.service

rm -frv /var/log/*
EOF

VOLUME ["/sys/fs/cgroup"]

CMD ["/usr/lib/systemd/systemd"]
