---

name: Arch Linux

on:
  push:
    paths:
      - Dockerfile.archlinux
      - .github/workflows/docker.yml
      - .github/workflows/archlinux.yml
  pull_request:
    paths:
      - Dockerfile.archlinux
      - .github/workflows/docker.yml
      - .github/workflows/archlinux.yml
  schedule:
    - cron: '0 6 * * 1'

jobs:
  docker:
    uses: $/.github/workflows/docker.yml
    with:
      name: Arch Linux
      distro: archlinux
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

...
