---

name: Debian Bullseye

on:
  push:
    paths:
      - Dockerfile.debian-bullseye
      - .github/workflows/docker.yml
      - .github/workflows/debian-bullseye.yml
  pull_request:
    paths:
      - Dockerfile.debian-bullseye
      - .github/workflows/docker.yml
      - .github/workflows/debian-bullseye.yml
  schedule:
    - cron: '0 6 * * 1'

jobs:
  docker:
    uses: $/.github/workflows/docker.yml
    with:
      name: Debian Bullseye
      distro: debian-bullseye
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

...
