---

name: Debian Trixie

on:
  push:
    paths:
      - Dockerfile.debian-trixie
      - .github/workflows/docker.yml
      - .github/workflows/debian-trixie.yml
  pull_request:
    paths:
      - Dockerfile.debian-trixie
      - .github/workflows/docker.yml
      - .github/workflows/debian-trixie.yml
  schedule:
    - cron: '0 6 * * 1'

jobs:
  docker:
    uses: $/.github/workflows/docker.yml
    with:
      name: Debian Trixie
      distro: debian-trixie
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

...
