---

name: Debian Bookworm

on:
  push:
    paths:
      - Dockerfile.debian-bookworm
      - .github/workflows/docker.yml
      - .github/workflows/debian-bookworm.yml
  pull_request:
    paths:
      - Dockerfile.debian-bookworm
      - .github/workflows/docker.yml
      - .github/workflows/debian-bookworm.yml
  schedule:
    - cron: '0 6 * * 1'

jobs:
  docker:
    uses: $/.github/workflows/docker.yml
    with:
      name: Debian Bookworm
      distro: debian-bookworm
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

...
