---

name: Rocky Linux 8

on:
  push:
    paths:
      - Dockerfile.rockylinux-8
      - .github/workflows/docker.yml
      - .github/workflows/rockylinux-8.yml
  pull_request:
    paths:
      - Dockerfile.rockylinux-8
      - .github/workflows/docker.yml
      - .github/workflows/rockylinux-8.yml

jobs:
  docker:
    uses: $/.github/workflows/docker.yml
    with:
      name: Rocky Linux 8
      distro: rockylinux-8
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

...
