---

name: Rocky Linux 10

on:
  push:
    paths:
      - Dockerfile.rockylinux-10
      - .github/workflows/docker.yml
      - .github/workflows/rockylinux-10.yml
  pull_request:
    paths:
      - Dockerfile.rockylinux-10
      - .github/workflows/docker.yml
      - .github/workflows/rockylinux-10.yml
  schedule:
    - cron: '0 6 * * 1'

jobs:
  docker:
    uses: $/.github/workflows/docker.yml
    with:
      name: Rocky Linux 10
      distro: rockylinux-10
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

...
