---

name: Rocky Linux 9

on:
  push:
    paths:
      - Dockerfile.rockylinux-9
      - .github/workflows/docker.yml
      - .github/workflows/rockylinux-9.yml
  pull_request:
    paths:
      - Dockerfile.rockylinux-9
      - .github/workflows/docker.yml
      - .github/workflows/rockylinux-9.yml
  schedule:
    - cron: '0 6 * * 1'

jobs:
  docker:
    uses: $/.github/workflows/docker.yml
    with:
      name: Rocky Linux 9
      distro: rockylinux-9
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

...
