---

name: Ubuntu Focal

on:
  push:
    paths:
      - Dockerfile.ubuntu-focal
      - .github/workflows/docker.yml
      - .github/workflows/ubuntu-focal.yml
  pull_request:
    paths:
      - Dockerfile.ubuntu-focal
      - .github/workflows/docker.yml
      - .github/workflows/ubuntu-focal.yml
  schedule:
    - cron: '0 6 * * 1'

jobs:
  docker:
    uses: $/.github/workflows/docker.yml
    with:
      name: Ubuntu Focal
      distro: ubuntu-focal
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

...
