---

name: Ubuntu Noble

on:
  push:
    paths:
      - Dockerfile.ubuntu-noble
      - .github/workflows/docker.yml
      - .github/workflows/ubuntu-noble.yml
  pull_request:
    paths:
      - Dockerfile.ubuntu-noble
      - .github/workflows/docker.yml
      - .github/workflows/ubuntu-noble.yml
  schedule:
    - cron: '0 6 * * 1'

jobs:
  docker:
    uses: $/.github/workflows/docker.yml
    with:
      name: Ubuntu Noble
      distro: ubuntu-noble
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

...
