---

name: Ubuntu Jammy

on:
  push:
    paths:
      - Dockerfile.ubuntu-jammy
      - .github/workflows/docker.yml
      - .github/workflows/ubuntu-jammy.yml
  pull_request:
    paths:
      - Dockerfile.ubuntu-jammy
      - .github/workflows/docker.yml
      - .github/workflows/ubuntu-jammy.yml
  schedule:
    - cron: '0 6 * * 1'

jobs:
  docker:
    uses: $/.github/workflows/docker.yml
    with:
      name: Ubuntu Jammy
      distro: ubuntu-jammy
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

...
